# Generated by Django 3.0.3 on 2020-07-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egs_locations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playfield',
            name='specialNotes',
            field=models.CharField(blank=True, default=None, help_text='Anything particularly groovy about this playfield', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='countBlackContainers',
            field=models.IntegerField(blank=True, default=None, help_text='The number of brown containers in this POI is >= this number', null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='countBrownContainers',
            field=models.IntegerField(blank=True, default=None, help_text='The number of brown containers in this POI is >= this number', null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='countRedContainers',
            field=models.IntegerField(blank=True, default=None, help_text='The number of red containers in this POI is >= this number', null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='countWhiteContainers',
            field=models.IntegerField(blank=True, default=None, help_text='The number of white containers in this POI is >= this number', null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='countYellowContainers',
            field=models.IntegerField(blank=True, default=None, help_text='The number of yellow containers in this POI is >= this number', null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='territory',
            field=models.ForeignKey(blank=True, default=None, help_text='Faction territory the system belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='egs_locations_app.Faction'),
        ),
    ]
