# Generated by Django 3.0.3 on 2020-07-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egs_locations_app', '0002_auto_20200706_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='countPurpleContainers',
            field=models.IntegerField(blank=True, default=None, help_text='The number of purple containers in this POI is >= this number', null=True),
        ),
    ]
